# Generated by Django 5.1.5 on 2025-02-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0003_alter_movie_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(max_length=10)),
                ('fk_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theatre_app.movie')),
            ],
        ),
    ]
