# Generated by Django 5.1.6 on 2025-02-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0004_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_time_slot',
        ),
    ]
