# Generated by Django 5.1.5 on 2025-02-25 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0006_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
