# Generated by Django 5.1.5 on 2025-02-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0007_showtime_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='date',
        ),
        migrations.CreateModel(
            name='ShowtimeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='theatre_app.showtime')),
            ],
        ),
    ]
