# Generated by Django 5.1.5 on 2025-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
