# Generated by Django 5.1.5 on 2025-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0010_seat_row_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
