# Generated by Django 5.1.6 on 2025-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0012_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
